name: Daily Selenium Run

on:
  schedule:
    - cron: "0 4 * * *"  # Every day at 4AM UTC
  workflow_dispatch:

jobs:
  run-selenium:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
            sudo apt-get update
            sudo apt-get install -y chromium-browser
            wget -q https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/137.0.7151.119/linux64/chromedriver-linux64.zip
            unzip chromedriver-linux64.zip
            sudo mv chromedriver-linux64/chromedriver /usr/bin/chromedriver
            sudo chmod +x /usr/bin/chromedriver
            rm -rf chromedriver-linux64*
            pip install selenium undetected-chromedriver pyvirtualdisplay


      - name: Run script with virtual display
        run: |
          xvfb-run -a python selenium_script.py

        
      - name: Upload screenshot
        uses: actions/upload-artifact@v3
        with:
            name: locator-screenshot
            path: page.png
